POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5BYmR1bGxhIiwiaWF0IjoxNjg1MjQ3NzQ0fQ.ntWlQTAfAmrh-WTnTZyUD3Gg34CNXpAGCoRPN2xPkgM

{
  "title": "Read Node doc",
  "description": "Read Node js doc from the website."
}

###
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5BYmR1bGxhIiwiaWF0IjoxNjg1MjQ3NzQ0fQ.ntWlQTAfAmrh-WTnTZyUD3Gg34CNXpAGCoRPN2xPkgM

###
GET http://localhost:3000/api/tasks/6472d72007f05e66519dc618
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5BYmR1bGxhIiwiaWF0IjoxNjg1MjQ3NzQ0fQ.ntWlQTAfAmrh-WTnTZyUD3Gg34CNXpAGCoRPN2xPkgM

###
PUT http://localhost:3000/api/tasks/6472d72007f05e66519dc618
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5BYmR1bGxhIiwiaWF0IjoxNjg1MjQ3NzQ0fQ.ntWlQTAfAmrh-WTnTZyUD3Gg34CNXpAGCoRPN2xPkgM

{
  "title": "Read Node documentation",
  "description": "Read Node js doc from the website."
}

###
DELETE http://localhost:3000/api/tasks/6472d72007f05e66519dc618
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5BYmR1bGxhIiwiaWF0IjoxNjg1MjQ3NzQ0fQ.ntWlQTAfAmrh-WTnTZyUD3Gg34CNXpAGCoRPN2xPkgM
